# Generated by Django 4.1 on 2022-12-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genres", "0002_genre_name_alter_genre_id"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="genres.genre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="premiere",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="title",
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
